// app/layout.tsx
import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import { googleFonts } from "./google-fonts";
import CustomEyeCursor from "@/components/CustomEyeCursor";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Kabiru",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${quicksand.variable}`}
      suppressHydrationWarning
    >
      <head>
        <link href={googleFonts.href} rel={googleFonts.rel} />
      </head>
      <body className="antialiased bg-white dark:bg-gray-900 text-black dark:text-white cursor-none">
        <CustomEyeCursor />
        {children}
      </body>
    </html>
  );
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// // app/layout.tsx
// import type { Metadata } from "next";
// import { Inter, Quicksand } from "next/font/google";
// import "./globals.css";
// import { googleFonts } from "./google-fonts";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// const quicksand = Quicksand({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-quicksand",
// });

// export const metadata: Metadata = {
//   title: "Kabiru",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${inter.variable} ${quicksand.variable}`}
//       suppressHydrationWarning
//     >
//       <head>
//         <link href={googleFonts.href} rel={googleFonts.rel} />
//       </head>
//       <body className="antialiased bg-white dark:bg-gray-900 text-black dark:text-white">
//         {/* <Header /> */}
//         {children}
//       </body>
//     </html>
//   );
// }
