import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ModeToggle } from "@/components/mode-toggle";
import { Providers } from "./theme-provider";
import { googleFonts } from "./google-fonts";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Kabiru",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${quicksand.variable}`}>
      <head>
        <link href={googleFonts.href} rel={googleFonts.rel} />
      </head>
      <Providers>
        <body className="antialiased">
          <Header />
          {children}
          <div className="fixed bottom-5 right-8 z-50 animate-bounce hover:animate-none">
            <ModeToggle />
          </div>
        </body>
      </Providers>
    </html>
  );
}
