// app/layout.tsx

import type { Metadata } from "next";
import { Inter, Quicksand, Protest_Revolution } from "next/font/google";

import "./globals.css";
import { googleFonts } from "./google-fonts";

// =========================
// Fonts
// =========================

const protest = Protest_Revolution({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-protest",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

// =========================
// Metadata
// =========================

export const metadata: Metadata = {
  title: "Kabiru",
  description: "Generated by create next app",
};

// =========================
// Layout
// =========================

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${inter.variable}
        ${quicksand.variable}
        ${protest.variable}
      `}
      suppressHydrationWarning
    >
      <head>
        <link href={googleFonts.href} rel={googleFonts.rel} />
      </head>

      <body className="font-tech antialiased bg-white dark:bg-gray-900 text-black dark:text-white">
        {children}
      </body>
    </html>
  );
}
